gitGraph
    commit id: "Initial commit"
    commit id: "Add main.c"
    branch feature
    checkout feature
    commit id: "Start feature"
    commit id: "Feature work"
    checkout main
    commit id: "Bugfix on main"
    checkout feature
    commit id: "Complete feature"
    checkout main
    merge feature tag: "v1.1"
    commit id: "Post-merge cleanup"
